#define VPU_PRIV_FS_READ 0x01
#define VPU_PRIV_FS_WRITE 0x02
#define VPU_PRIV_RFS_ACCESS 0x04
#define VPU_PRIV_SIGNALS 0x08
#define VPU_PRIV_MODULES 0x10
#define VPU_PRIV_SYSTEM 0x20

#define VPU_PRIV_ROOT 0x80
